import type { Product, ServiceProvider, Shop } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) =>
  PlaceHolderImages.find(p => p.id === id) || { imageUrl: '', imageHint: '' };

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Автоодеяло',
    description: 'Утепленное одеяло для двигателя для сохранения тепла.',
    price: 3500,
    ...findImage('product-blanket'),
    shopId: 'shop-1',
    delivery: true,
    deliveryPrice: 300,
    pickup: true,
  },
  {
    id: 'prod-2',
    name: 'AGM аккумулятор',
    description: 'Высокопроизводительный аккумулятор для сильных морозов.',
    price: 15000,
    ...findImage('product-battery'),
    shopId: 'shop-2',
    delivery: true,
    deliveryPrice: 500,
    pickup: true,
  },
  {
    id: 'prod-3',
    name: 'Пусковое устройство',
    description: 'Портативное устройство для запуска автомобиля.',
    price: 8500,
    ...findImage('product-jumper'),
    shopId: 'shop-1',
    delivery: false,
    pickup: true,
  },
  {
    id: 'prod-4',
    name: 'Антигель для дизеля',
    description: 'Предотвращает застывание дизельного топлива на морозе.',
    price: 1200,
    ...findImage('product-antifreeze'),
    shopId: 'shop-3',
    delivery: true,
    deliveryPrice: 0,
    pickup: true,
  },
  {
    id: 'prod-5',
    name: 'Компактная лопата',
    description: 'Прочная и легкая снеговая лопата.',
    price: 2000,
    ...findImage('product-shovel'),
    shopId: 'shop-4',
    delivery: false,
    pickup: true,
  },
  {
    id: 'prod-6',
    name: 'Цепи противоскольжения',
    description: 'Цепи на шины для улучшения сцепления на льду.',
    price: 6000,
    ...findImage('product-chains'),
    shopId: 'shop-5',
    delivery: true,
    deliveryPrice: 400,
    pickup: false,
  },
];

export const mockProviders: ServiceProvider[] = [
  {
    id: 'prov-1',
    name: 'Алексей',
    avatarUrl: findImage('provider-1').imageUrl,
    rating: 4.9,
    distance: 2.5,
    vehicle: 'Toyota Hilux',
  },
  {
    id: 'prov-2',
    name: 'Михаил',
    avatarUrl: findImage('provider-2').imageUrl,
    rating: 4.8,
    distance: 4.1,
    vehicle: 'УАЗ Патриот',
  },
  {
    id: 'prov-3',
    name: 'Семен',
    avatarUrl: findImage('provider-3').imageUrl,
    rating: 4.7,
    distance: 7.8,
    vehicle: 'Mitsubishi L200',
  },
];

export const mockShops: Shop[] = [
  {
    id: 'shop-1',
    name: 'Авто-Мир',
    type: 'store',
    address: 'г. Якутск, ул. Чернышевского, 66',
    workingHours: 'Пн-Вс: 9:00 - 20:00',
    imageUrl: findImage('shop-1').imageUrl,
    imageHint: findImage('shop-1').imageHint,
    bannerUrl: findImage('shop-1-banner').imageUrl,
    bannerHint: findImage('shop-1-banner').imageHint,
    description: 'Все для вашего авто. Качественные запчасти и аксессуары.',
  },
  {
    id: 'shop-2',
    name: 'Все для авто',
    type: 'store',
    address: 'г. Якутск, ул. Автодорожная, 11/4',
    workingHours: 'Пн-Пт: 10:00 - 19:00',
    imageUrl: findImage('shop-2').imageUrl,
    imageHint: findImage('shop-2').imageHint,
    bannerUrl: findImage('shop-2-banner').imageUrl,
    bannerHint: findImage('shop-2-banner').imageHint,
    description: 'Широкий ассортимент автотоваров по доступным ценам.',
  },
  {
    id: 'shop-3',
    name: 'Шинный двор',
    type: 'person',
    imageUrl: findImage('shop-3').imageUrl,
    imageHint: findImage('shop-3').imageHint,
    bannerUrl: findImage('shop-3-banner').imageUrl,
    bannerHint: findImage('shop-3-banner').imageHint,
    description: 'Шины и диски от ведущих производителей. Частный продавец.',
  },
  {
    id: 'shop-4',
    name: 'Ремонт-Профи',
    type: 'store',
    address: 'г. Якутск, ул. 50 лет Советской Армии, 33',
    workingHours: 'Круглосуточно',
    imageUrl: findImage('shop-4').imageUrl,
    imageHint: findImage('shop-4').imageHint,
    bannerUrl: findImage('shop-4-banner').imageUrl,
    bannerHint: findImage('shop-4-banner').imageHint,
    description:
      'Инструменты и расходники для профессионального ремонта.',
  },
  {
    id: 'shop-5',
    name: 'Запчасти-Экспресс',
    type: 'person',
    imageUrl: findImage('shop-5').imageUrl,
    imageHint: findImage('shop-5').imageHint,
    bannerUrl: findImage('shop-5-banner').imageUrl,
    bannerHint: findImage('shop-5-banner').imageHint,
    description:
      'Быстрая доставка оригинальных и аналоговых запчастей от частного лица.',
  },
  {
    id: 'shop-6',
    name: 'Японские запчасти',
    type: 'store',
    address: 'г. Якутск, ул. Пояркова, 20',
    workingHours: 'Пн-Сб: 9:00 - 18:00',
    imageUrl: findImage('shop-1').imageUrl,
    imageHint: findImage('shop-1').imageHint,
    bannerUrl: findImage('shop-1-banner').imageUrl,
    bannerHint: findImage('shop-1-banner').imageHint,
    description: 'Все для японских автомобилей: от фильтров до двигателей.',
  },
];
